- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cog
  - Core
  - Fland
  - Marathon
  - MetaStation
  - Oasis
  - Omega
  - Packed
  - Reach
  #- Train
  - Driller
  - Lighthouse
  - Tehtra
  - Elstation
